refactor: get rid of unnecessery code, update mc-jsonlogger
MapColonies/discrete-worker pull request #1
Opened 2021-01-10 12:50 UTC by AnguIar

2021-01-10 14:02 UTC, asafMasa requested changes

2021-01-10 14:08 UTC, AnguIar commented on src/main.py
> +            self.log.info("starting service")
Currently the code will not run since it has nothing in the `try{} catch{}` section. Some code will be added soon...

2021-01-10 20:42 UTC, asafMasa requested changes
good job

2021-01-10 20:42 UTC, asafMasa commented on src/task_handler.py
> +                if result:
log for false result?

2021-01-10 20:42 UTC, asafMasa commented on src/task_handler.py
> +            return False
should the return false be in finally?

2021-01-10 20:42 UTC, asafMasa commented on src/task_handler.py
> +            return True
add // todo: gdal2tiles will be added here

2021-01-10 20:42 UTC, asafMasa commented on src/task_handler.py
> +            self.log.info(f'Executing task')
add task id for all logs of specific task including when you commit it to kafka

2021-01-10 20:42 UTC, asafMasa commented on logger/jsonLogger.py
> +                                   'type': config['logger']['type'],
check that file and console loggers work

2021-01-11 09:39 UTC, asafMasa requested changes

2021-01-11 09:39 UTC, asafMasa commented on confd/production.tmpl
> +    "mandatory_task_fields": ["fileName", "url", "bbox", "taskId", "directoryName"]
are all the parameters in the config file necessary?

2021-01-11 09:39 UTC, asafMasa commented on confd/production.toml
> +    "/configuration/exporter/worker/s3/download/expired/time"
are all the parameters in the toml file necessary?

2021-01-11 09:39 UTC, asafMasa commented on src/task_handler.py
>              self.log.error(f'Error occurred while exporting: {e}.')
add task id to exception log if possible

2021-01-11 09:45 UTC, asafMasa commented
you didn't answer to all of my previous comments

2021-01-11 10:03 UTC, asafMasa approved these changes

2021-01-11 10:04 UTC, merged