Fs support
MapColonies/discrete-worker pull request #20
Opened 2021-01-18 16:11 UTC by AnguIar

2021-01-18 16:20 UTC, asafMasa approved these changes

2021-01-18 16:20 UTC, asafMasa commented on src/main.py
> +            self.__utilities.create_folder(worker_constants.TILES_OUTPUT_FOLDER_NAME)
if FS

2021-01-19 08:57 UTC, asafMasa requested changes
🚀 Good job!

2021-01-19 08:57 UTC, asafMasa commented on src/main.py
> +            if (storage_provider == StorageProvider.S3):
why not to use "else"?

2021-01-19 08:57 UTC, asafMasa commented on confd/production.tmpl
> +        "internal_outputs_path": "{{ getv "/configuration/discrete/worker/fs/internal/outputs/path" "./tiles_outputs"}}"
change in toml file?

2021-01-19 09:02 UTC, AnguIar commented on confd/production.tmpl
> +        "internal_outputs_path": "{{ getv "/configuration/discrete/worker/fs/internal/outputs/path" "./tiles_outputs"}}"
we change the value, not the environment variable key
no need to change in toml file

2021-01-19 09:22 UTC, asafMasa approved these changes
👑

2021-01-19 09:39 UTC, merged