feat: removed kafka, added priority queue manage package
MapColonies/discrete-worker pull request #51
Opened 2021-07-05 11:07 UTC by CL-SHLOMIKONCHA

2021-07-05 12:00 UTC, asafMasa requested changes

2021-07-05 12:00 UTC, asafMasa commented on confd/production.tmpl
> +        "heartbeat_interval_ms": {{ getv "/configuration/discrete/worker/queue/heartbeat/interval/ms" "0.2" }},
seconds

2021-07-05 12:00 UTC, asafMasa commented on confd/production.toml
> +    "/configuration/discrete/worker/queue/dequeue/interval/ms",
seconds

2021-07-05 12:00 UTC, asafMasa commented on src/handler.py
> +                        self.log.error("Validation error - could not process request. Comitting from queue")
log the job and task id (and discreteID, version)

2021-07-05 12:00 UTC, asafMasa commented on src/handler.py
> +                        self.log.error("Validation error - could not process request and could not save status to DB. Comitting from queue")
log the job or task id if exists  (and discreteID, version)

2021-07-05 12:00 UTC, asafMasa commented on src/handler.py
> +                task_id = task["id"]
is there a log about the dequeud task before starting to work on it? if not add that log

2021-07-05 12:00 UTC, asafMasa commented on src/worker.py
> +            .format(job_data['jobId'], job_data['id'], job_data['parameters']['discreteId'], job_data['parameters']['version']))
.format(job_data['jobId'], job_data['id'], job_data['parameters']['discreteId'], job_data['parameters']['version']))
try to put in utils, and use the same format for several logs

2021-07-05 12:01 UTC, CL-SHLOMIKONCHA commented on confd/production.tmpl
> +        "heartbeat_interval_ms": {{ getv "/configuration/discrete/worker/queue/heartbeat/interval/ms" "0.2" }},
fixed in e6f2d1f

2021-07-05 12:01 UTC, CL-SHLOMIKONCHA commented on confd/production.toml
> +    "/configuration/discrete/worker/queue/dequeue/interval/ms",
e6f2d1f fixed

2021-07-05 13:04 UTC, CL-SHLOMIKONCHA commented on src/worker.py
> +            .format(job_data['jobId'], job_data['id'], job_data['parameters']['discreteId'], job_data['parameters']['version']))
c9b0d53 fixed

2021-07-05 13:05 UTC, CL-SHLOMIKONCHA commented on src/handler.py
> +                        self.log.error("Validation error - could not process request and could not save status to DB. Comitting from queue")
c9b0d53  fixed

2021-07-05 13:10 UTC, CL-SHLOMIKONCHA commented on src/handler.py
> +                task_id = task["id"]
dffa9f2 fixed

2021-07-06 07:02 UTC, asafMasa requested changes
👍

2021-07-06 07:02 UTC, asafMasa commented on src/handler.py
> +                              .format(task_values))
utilities.task_format_log

2021-07-06 07:02 UTC, asafMasa commented on src/worker.py
>          tiles_location = '{0}/{1}'.format(self.tiles_folder_location, job_data['parameters']['discreteId'])
remove zoom_levels

2021-07-06 07:26 UTC, CL-SHLOMIKONCHA commented on src/handler.py
>          parameters = task_values["parameters"]
fixed in 
5b661e0

2021-07-06 07:27 UTC, CL-SHLOMIKONCHA commented on src/handler.py
> +                              .format(task_values))
fixed in 
1246757

2021-07-06 07:27 UTC, CL-SHLOMIKONCHA commented on src/handler.py
> +                              .format(task_values))
& 94a6289

2021-07-06 07:44 UTC, CL-SHLOMIKONCHA commented on src/handler.py
>                      if task_id and job_id:
removed in 
1246757

2021-07-06 07:45 UTC, CL-SHLOMIKONCHA commented on src/utilities.py
> +    return "jobId: {0}, taskId: {1}, discreteID: {2}, version: {3}"\
fixed in 
1246757

2021-07-06 07:45 UTC, CL-SHLOMIKONCHA commented on src/worker.py
>          tiles_location = '{0}/{1}'.format(self.tiles_folder_location, job_data['parameters']['discreteId'])
removed

2021-07-11 06:27 UTC, asafMasa approved these changes

2021-07-11 12:27 UTC, merged